webroot/app/models.py
from flask_login import UserMixin
from app import db
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

webroot/app/login/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, validators
from ..models import User


class LoginForm(FlaskForm):
    username = StringField('Username', [validators.DataRequired(), validators.Length(min=4, max=25)])
    password = PasswordField('Password', [validators.DataRequired()])
    submit = SubmitField('Log in')


class RegForm(FlaskForm):
    username = StringField('Username', [validators.DataRequired(), validators.Length(min=4, max=25)])
    password = PasswordField('Password', [validators.DataRequired(),
                                          validators.EqualTo('confirm', message='password must match')])
    confirm = PasswordField('Confirm password', [validators.DataRequired()])
    submit = SubmitField('Register')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise validators.ValidationError('Username already in use.')

webroot/app/__init__.py
import eventlet
import redis
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_socketio import SocketIO
from config import config

eventlet.monkey_patch()

pool = redis.ConnectionPool(host='127.0.0.1', port=6379, db=0)
r = redis.Redis(connection_pool=pool)

children_socket = SocketIO(message_queue='redis://127.0.0.1:6379/0')

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
socketio = SocketIO()
login_manager.login_view = 'login.do_login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    socketio.init_app(app, message_queue='redis://127.0.0.1:6379/0', async_mode="eventlet")

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .login import login as login_bp
    app.register_blueprint(login_bp, url_prefix='/login')

    return app

webroot/app/login/__init__.py
from flask import Blueprint

login = Blueprint('login', __name__)

from . import views

webroot/app/login/views.py
from flask import redirect, url_for, render_template, flash, request
from flask_login import login_user, login_required, logout_user
from app.login import login
from app.models import User
from .forms import LoginForm, RegForm
from app import db


@login.route('/', methods=['GET', 'POST'])
def do_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            return redirect(request.args.get('next') or url_for('main.get_lobby'))
        flash('Invalid username or password')
    return render_template('login.html', form=form)


@login.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out')
    return redirect(url_for('main.index'))


@login.route('/register', methods=['GET', 'POST'])
def register():
    form = RegForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('You can now login')
        print('ready to redirect to login page')
        return redirect(url_for('login.do_login'))
    if not (form.password.data==form.confirm.data):
        flash('Confirm password must be the same as Password')
    return render_template('register.html', form=form)

webroot/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, events, lobby

webroot/app/main/views.py
from . import main
from flask import url_for, redirect
from flask_login import current_user


@main.route('/')
def index():
    if current_user.is_authenticated() is False:
        return redirect(url_for('login.do_login'))
    else:
        return redirect(url_for('main.get_lobby'))
    # return send_from_directory('static', 'room.html')

webroot/app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Demo Web{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">Demo Web</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if current_user.is_authenticated() %}
                <li><a href="{{ url_for('posts.post_list') }}">Home</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated() %}
                <li><a href="{{ url_for('auth.logout') }}">Sign Out</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Sign In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

webroot/app/templates/lobby.html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<title>Tetris Game Lobby</title>
<link rel="stylesheet" title="text/css" href="/static/lobby.css" />
</head>

<body>

<div class="box">
<div id="left">
	<div id="current-user">
	<ul id="user-info">
		<li>{{ current_user.username }}</li>
	</ul>
	
	<button type="button" id="logout" onclick="{location.href='{{ url_for('login.logout')}}'}">
		<img src="/static/image/logout_btn.png">
	</button>
	</div>

	<div id="playerlist">
		<p id="list_label">spare players:</p>
		<ul id="players">
		</ul>
	</div>
</div>

<div id="right">
	<div id="rooms-outline">
	<ul id="rooms">
	</ul>
	</div>
	
	<div id="newroom">
	<button type="button" id="newroom_btn">
	</button>
	</div>

	<div id="chat-area">
		<div id="msg-area">
		<ul id="chat-msgs">
		</ul>
		</div>
		<div id="chat-input">
		<div id="chat-box">
			<input type="text"></input>
		</div>
		<button type="button" id="chat-submit">
			<img src="/static/image/submit.png">
		</button>
		</div>
	</div>
</div>
</div>

<script src="/static/socket.io.js"></script>
<script src="/static/lobby.js"></script>

</body>
</html>

webroot/app/templates/login.html
<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8">
<title>Login</title>
<link rel="stylesheet" title="text/css" href="/static/login.css" />
</head>

<body>

<div id="login_ico">
	<img src="/static/image/login_ico.png" width="500">
</div>

{% for message in get_flashed_messages() %}
	<ul class="alert">
		<li>{{ message }}</li>
	</ul>
{% endfor %}

<div id="box">
	<div id="user">
		<form class="form" method="POST">
			{{ form.hidden_tag() }}
			{{ form.username.label }}
			{{ form.username() }}
			{{ form.password.label }}
			{{ form.password() }}
			{{ form.submit(value="", id="login_btn") }}
		</form>
	</div>
</div>


<button type="button" id="signup_btn" onclick="{location.href='{{ url_for('login.register')}}'}"></button>

<img id="loginbg" src="/static/image/login_bg.png">

</body>

</html>

webroot/app/templates/register.html
<!DOCTYPE html>

<html>
<head>
<meta charset="utf-8">
<title>Sign Up</title>
<link rel="stylesheet" title="text/css" href="/static/register.css" />
</head>

<body>

<div id="signup_ico">
	<img src="/static/image/signup_ico.png" width="500">
</div>

{% for message in get_flashed_messages() %}
	<ul class="alert">
		<li>{{ message }}</li>
	</ul>
{% endfor %}

<div id="box">
	<div id="user">
		<form class="form" method="POST">
			{{ form.hidden_tag() }}
			{{ form.username.label }}
			{{ form.username() }}
			{{ form.password.label }}
			{{ form.password() }}
			{{ form.confirm.label }}
			{{ form.confirm() }}
			{{ form.submit(value="", id="signup_btn") }}
		</form>
	</div>
</div>

<button type="button" id="login_btn" onclick="{location.href='{{ url_for('login.do_login')}}'}"></button>

<img id="loginbg" src="/static/image/login_bg.png">

</body>

</html>

webroot/app/templates/room.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Tetris Game Room</title>
<link rel="stylesheet" title="text/css" href="/static/room.css" />
<script type="text/javascript" src="/static/phaser.js"></script>
<script type="text/javascript" src="/static/socket.io.js"></script>
</head>

<body>

<div id="box">
<div id="left">
<div id="user-info">
	<div id="user-info-1">
	</div>
	<div id="user-info-2">
	</div>
</div>

<div id="chat-area">
	<div id="msg-area">
	<ul id="chat-msgs">
	</ul>
	</div>
	<div id="chat-input">
		<div id="chat-box">
			<input type="text"></input>
		</div>
		<button type="button" id="chat-submit">
			<img src="/static/image/submit.png">
		</button>
	</div>
</div>
</div>

<div id="right">
	<div id="game-area">
		<div id="game-l"></div>
		<div id="next-l"></div>
		<div id="next-r"></div>
		<div id="game-r"></div>
	</div>

	<div id="buttons">
		<button type="button" id="game-ready">
			<img src="/static/image/ready.png" id="ready-img">
		</button>
		<button type="button" id="exit" onclick="{location.href='{{ url_for('main.get_lobby') }}'}">
			<img src="/static/image/exit.png">
		</button>
	</div>
</div>

</div>
<script src="/static/game.js"></script>
</body>
</html>